#############################################################################
# Makefile for building: QtPersons
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  QtPersons.pro
# Template: app
# Command: /Users/kthorri/Qt/5.3/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=x86_64 CONFIG+=x86_64 -o Makefile QtPersons.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Forritun/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Forritun/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Forritun/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Forritun/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Users/kthorri/Qt/5.3/clang_64/mkspecs/macx-clang -I. -I/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers -I/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -F/Users/kthorri/Qt/5.3/clang_64/lib
LINK          = /Applications/Forritun/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Forritun/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/kthorri/Qt/5.3/clang_64/lib -framework QtSql -framework QtCore 
AR            = /Applications/Forritun/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Forritun/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/kthorri/Qt/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		person.cpp \
		consoleui.cpp \
		search.cpp \
		sort.cpp \
		computer.cpp \
		printui.cpp \
		computerrepository.cpp \
		personsrepository.cpp \
		personsservice.cpp \
		computersservice.cpp \
		connectionsrepository.cpp \
		connection.cpp \
		connectionsservice.cpp 
OBJECTS       = main.o \
		person.o \
		consoleui.o \
		search.o \
		sort.o \
		computer.o \
		printui.o \
		computerrepository.o \
		personsrepository.o \
		personsservice.o \
		computersservice.o \
		connectionsrepository.o \
		connection.o \
		connectionsservice.o
DIST          = /Users/kthorri/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/qdevice.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/unix.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/mac.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/macx.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/clang.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/qconfig.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/qt.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/resources.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/moc.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/lex.prf \
		QtPersons.pro main.cpp \
		person.cpp \
		consoleui.cpp \
		search.cpp \
		sort.cpp \
		computer.cpp \
		printui.cpp \
		computerrepository.cpp \
		personsrepository.cpp \
		personsservice.cpp \
		computersservice.cpp \
		connectionsrepository.cpp \
		connection.cpp \
		connectionsservice.cpp
QMAKE_TARGET  = QtPersons
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = QtPersons

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Forritun/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QtPersons.pro /Users/kthorri/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf /Users/kthorri/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/qdevice.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/unix.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/mac.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/macx.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/clang.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/qconfig.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/qt.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/resources.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/moc.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/lex.prf \
		QtPersons.pro \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/QtSql.prl \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=x86_64 CONFIG+=x86_64 -o Makefile QtPersons.pro
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/qdevice.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/device_config.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/unix.conf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/mac.conf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/macx.conf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/clang.conf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/qconfig.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/qt_config.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/default_pre.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/default_post.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/warn_on.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/qt.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/resources.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/moc.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/exceptions.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/yacc.prf:
/Users/kthorri/Qt/5.3/clang_64/mkspecs/features/lex.prf:
QtPersons.pro:
/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/QtSql.prl:
/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=x86_64 CONFIG+=x86_64 -o Makefile QtPersons.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/QtPersons1.0.0 || mkdir -p .tmp/QtPersons1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/QtPersons1.0.0/ && $(COPY_FILE) --parents person.h consoleui.h search.h sort.h computer.h printui.h computerrepository.h personsrepository.h personsservice.h computersservice.h connectionsrepository.h connection.h connectionsservice.h .tmp/QtPersons1.0.0/ && $(COPY_FILE) --parents main.cpp person.cpp consoleui.cpp search.cpp sort.cpp computer.cpp printui.cpp computerrepository.cpp personsrepository.cpp personsservice.cpp computersservice.cpp connectionsrepository.cpp connection.cpp connectionsservice.cpp .tmp/QtPersons1.0.0/ && (cd `dirname .tmp/QtPersons1.0.0` && $(TAR) QtPersons1.0.0.tar QtPersons1.0.0 && $(COMPRESS) QtPersons1.0.0.tar) && $(MOVE) `dirname .tmp/QtPersons1.0.0`/QtPersons1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QtPersons1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp consoleui.h \
		personsservice.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		person.h \
		search.h \
		computer.h \
		personsrepository.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		computerrepository.h \
		computersservice.h \
		sort.h \
		printui.h \
		connectionsservice.h \
		connectionsrepository.h \
		connection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

person.o: person.cpp person.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o person.o person.cpp

consoleui.o: consoleui.cpp consoleui.h \
		personsservice.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		person.h \
		search.h \
		computer.h \
		personsrepository.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		computerrepository.h \
		computersservice.h \
		sort.h \
		printui.h \
		connectionsservice.h \
		connectionsrepository.h \
		connection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o consoleui.o consoleui.cpp

search.o: search.cpp search.h \
		person.h \
		computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o search.o search.cpp

sort.o: sort.cpp sort.h \
		person.h \
		computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sort.o sort.cpp

computer.o: computer.cpp computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o computer.o computer.cpp

printui.o: printui.cpp printui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printui.o printui.cpp

computerrepository.o: computerrepository.cpp computerrepository.h \
		person.h \
		computer.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o computerrepository.o computerrepository.cpp

personsrepository.o: personsrepository.cpp personsrepository.h \
		person.h \
		computer.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o personsrepository.o personsrepository.cpp

personsservice.o: personsservice.cpp personsservice.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		person.h \
		search.h \
		computer.h \
		personsrepository.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		computerrepository.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o personsservice.o personsservice.cpp

computersservice.o: computersservice.cpp computersservice.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		person.h \
		search.h \
		computer.h \
		personsrepository.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		computerrepository.h \
		sort.h \
		printui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o computersservice.o computersservice.cpp

connectionsrepository.o: connectionsrepository.cpp connectionsrepository.h \
		connection.h \
		personsservice.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		person.h \
		search.h \
		computer.h \
		personsrepository.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		computerrepository.h \
		computersservice.h \
		sort.h \
		printui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionsrepository.o connectionsrepository.cpp

connection.o: connection.cpp connection.h \
		personsservice.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		person.h \
		search.h \
		computer.h \
		personsrepository.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		computerrepository.h \
		computersservice.h \
		sort.h \
		printui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connection.o connection.cpp

connectionsservice.o: connectionsservice.cpp connectionsservice.h \
		connectionsrepository.h \
		connection.h \
		personsservice.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		person.h \
		search.h \
		computer.h \
		personsrepository.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/kthorri/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		computerrepository.h \
		computersservice.h \
		sort.h \
		printui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionsservice.o connectionsservice.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

