#############################################################################
# Makefile for building: CSC-WindowApp.app/Contents/MacOS/CSC-WindowApp
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  CSC-WindowApp.pro
# Template: app
# Command: /Users/Fanney/Qt/5.3/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile CSC-WindowApp.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Forritun/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Forritun/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Forritun/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Forritun/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Users/Fanney/Qt/5.3/clang_64/mkspecs/macx-clang -I. -I/Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers -I/Users/Fanney/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Forritun/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Forritun/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers/ -I. -F/Users/Fanney/Qt/5.3/clang_64/lib
LINK          = /Applications/Forritun/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Forritun/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/Fanney/Qt/5.3/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework QtSql -framework OpenGL -framework AGL 
AR            = /Applications/Forritun/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Forritun/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/Fanney/Qt/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		computer.cpp \
		computerrepository.cpp \
		computersservice.cpp \
		connection.cpp \
		connectionsrepository.cpp \
		connectionsservice.cpp \
		person.cpp \
		personsrepository.cpp \
		personsservice.cpp \
		search.cpp \
		sort.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		computer.o \
		computerrepository.o \
		computersservice.o \
		connection.o \
		connectionsrepository.o \
		connectionsservice.o \
		person.o \
		personsrepository.o \
		personsservice.o \
		search.o \
		sort.o \
		moc_mainwindow.o
DIST          = /Users/Fanney/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/qdevice.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/unix.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/mac.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/macx.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/clang.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/qconfig.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/qt.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/resources.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/moc.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/uic.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/lex.prf \
		CSC-WindowApp.pro main.cpp \
		mainwindow.cpp \
		computer.cpp \
		computerrepository.cpp \
		computersservice.cpp \
		connection.cpp \
		connectionsrepository.cpp \
		connectionsservice.cpp \
		person.cpp \
		personsrepository.cpp \
		personsservice.cpp \
		search.cpp \
		sort.cpp
QMAKE_TARGET  = CSC-WindowApp
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = CSC-WindowApp.app/Contents/MacOS/CSC-WindowApp

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Forritun/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile CSC-WindowApp.app/Contents/PkgInfo CSC-WindowApp.app/Contents/Resources/empty.lproj CSC-WindowApp.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d CSC-WindowApp.app/Contents/MacOS/ || mkdir -p CSC-WindowApp.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CSC-WindowApp.pro /Users/Fanney/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf /Users/Fanney/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/qdevice.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/unix.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/mac.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/macx.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/clang.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/qconfig.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/qt.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/resources.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/moc.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/uic.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/lex.prf \
		CSC-WindowApp.pro \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/QtSql.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile CSC-WindowApp.pro
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/qdevice.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/device_config.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/unix.conf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/mac.conf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/macx.conf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/clang.conf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/qconfig.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/qt_config.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/default_pre.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/default_post.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/warn_on.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/qt.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/resources.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/moc.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/uic.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/exceptions.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/yacc.prf:
/Users/Fanney/Qt/5.3/clang_64/mkspecs/features/lex.prf:
CSC-WindowApp.pro:
/Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Fanney/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/QtSql.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile CSC-WindowApp.pro

qmake_all: FORCE

CSC-WindowApp.app/Contents/PkgInfo: 
	@test -d CSC-WindowApp.app/Contents || mkdir -p CSC-WindowApp.app/Contents
	@$(DEL_FILE) CSC-WindowApp.app/Contents/PkgInfo
	@echo "APPL????" >CSC-WindowApp.app/Contents/PkgInfo
CSC-WindowApp.app/Contents/Resources/empty.lproj: 
	@test -d CSC-WindowApp.app/Contents/Resources || mkdir -p CSC-WindowApp.app/Contents/Resources
	@touch CSC-WindowApp.app/Contents/Resources/empty.lproj
	
CSC-WindowApp.app/Contents/Info.plist: 
	@test -d CSC-WindowApp.app/Contents || mkdir -p CSC-WindowApp.app/Contents
	@$(DEL_FILE) CSC-WindowApp.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.CSC-WindowApp,g" -e "s,@EXECUTABLE@,CSC-WindowApp,g" -e "s,@TYPEINFO@,????,g" /Users/Fanney/Qt/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >CSC-WindowApp.app/Contents/Info.plist
dist: 
	@test -d .tmp/CSC-WindowApp1.0.0 || mkdir -p .tmp/CSC-WindowApp1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/CSC-WindowApp1.0.0/ && $(COPY_FILE) --parents mainwindow.h computer.h computerrepository.h computersservice.h connection.h connectionsrepository.h connectionsservice.h person.h personsrepository.h personsservice.h readperson.h search.h sort.h .tmp/CSC-WindowApp1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp computer.cpp computerrepository.cpp computersservice.cpp connection.cpp connectionsrepository.cpp connectionsservice.cpp person.cpp personsrepository.cpp personsservice.cpp search.cpp sort.cpp .tmp/CSC-WindowApp1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/CSC-WindowApp1.0.0/ && (cd `dirname .tmp/CSC-WindowApp1.0.0` && $(TAR) CSC-WindowApp1.0.0.tar CSC-WindowApp1.0.0 && $(COMPRESS) CSC-WindowApp1.0.0.tar) && $(MOVE) `dirname .tmp/CSC-WindowApp1.0.0`/CSC-WindowApp1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CSC-WindowApp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r CSC-WindowApp.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		personsservice.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		personsrepository.h \
		person.h \
		computer.h \
		mainwindow.h
	/Users/Fanney/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/Fanney/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/Fanney/Dropbox/Skoli/School2014Fall/VerklegtNamkeid/Qt/hairy-ironman -I/Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Headers -I/Users/Fanney/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/Fanney/Qt/5.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/Fanney/Qt/5.3/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		personsservice.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		personsrepository.h \
		person.h \
		computer.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		personsservice.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		personsrepository.h \
		person.h \
		computer.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

computer.o: computer.cpp computer.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o computer.o computer.cpp

computerrepository.o: computerrepository.cpp computerrepository.h \
		person.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o computerrepository.o computerrepository.cpp

computersservice.o: computersservice.cpp computersservice.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		computerrepository.h \
		person.h \
		computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o computersservice.o computersservice.cpp

connection.o: connection.cpp connection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connection.o connection.cpp

connectionsrepository.o: connectionsrepository.cpp connectionsrepository.h \
		connection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionsrepository.o connectionsrepository.cpp

connectionsservice.o: connectionsservice.cpp connectionsservice.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		connectionsrepository.h \
		connection.h \
		personsrepository.h \
		person.h \
		computer.h \
		computerrepository.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionsservice.o connectionsservice.cpp

person.o: person.cpp person.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o person.o person.cpp

personsrepository.o: personsrepository.cpp personsrepository.h \
		person.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o personsrepository.o personsrepository.cpp

personsservice.o: personsservice.cpp personsservice.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QtSql \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriver.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldriverplugin.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlfield.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlindex.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlresult.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaldelegate.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qtsqlversion.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		personsrepository.h \
		person.h \
		computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o personsservice.o personsservice.cpp

search.o: search.cpp search.h \
		person.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o search.o search.cpp

sort.o: sort.cpp sort.h \
		person.h \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Users/Fanney/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		computer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sort.o sort.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

